version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region <REGION>)
      - IMAGE_URI="<USERID>.dkr.ecr.<REGION>.amazonaws.com/playlist"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t playlist .
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker tag playlist:latest <USERID>.dkr.ecr.<REGION>.amazonaws.com/playlist:latest
      - docker push <USERID>.dkr.ecr.<REGION>.amazonaws.com/playlist:latest
