version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - IMAGE_URI="793766633546.dkr.ecr.us-east-1.amazonaws.com/songs"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t songs .
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker tag api:latest 793766633546.dkr.ecr.us-west-2.amazonaws.com/songs:v1
      - docker push 793766633546.dkr.ecr.us-east-1.amazonaws.com/api:latest
